<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <SupportedPlatform Include="windows" />
    <Reference Include="PaintDotNet.Data">
      <Private>false</Private>
      <HintPath>C:\Program Files\Paint.NET\PaintDotNet.Data.dll</HintPath>
    </Reference>

    <ProjectReference Include="../openraster/OpenRaster Filetype.csproj" />
  </ItemGroup>
</Project>
