[package]
name = "pdn-export"
edition = "2024"

[dependencies]
color-eyre.workspace = true
thiserror.workspace = true
clap = { version = "4.5", features = ["derive"] }
directories = "6.0"
toml_edit = { version = "0.22.26" }

[target.'cfg(windows)'.dependencies]
netcorehost = { version = "0.17.0", default-features = false, features = ["net8_0", "nethost"], optional = true}

[features]
pdn-sys = ["dep:netcorehost"]
