[package]
name = "pdn-conv"
edition = "2024"

[dependencies]
eyre.workspace = true
thiserror.workspace = true
directories = "6"
toml_edit = { version = "0.24" }

[target.'cfg(windows)'.dependencies]
netcorehost = { version = "0.20.0", default-features = false, features = ["net8_0", "nethost"], optional = true}

[features]
pdn-sys = ["dep:netcorehost"]

[lints]
workspace = true