[package]
name = "PdnBatchConverter"
edition = "2024"

[dependencies]
eyre.workspace = true
thiserror.workspace = true
rfd = "0.15"
walkdir = "2"
tokio = { version = "1", features = ["sync", "rt"] }

iced = { git = "https://github.com/iced-rs/iced.git", features = ["tokio", "sipper", "advanced", "svg"] }
pdn-conv = { path = "../shared" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.60", features = ["Win32_UI_WindowsAndMessaging", "Win32_System_LibraryLoader"] }

[build-dependencies]
embed-resource = "3"

[features]
pdn-sys = ["pdn-conv/pdn-sys"]

[lints]
workspace = true
