name: Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Name'
  push:
    branches: [ "trunk" ]
    paths-ignore:
      - '.assets'
      - 'README.md'
      - 'CONTRIBUTING.md'
  pull_request:
    branches: [ "trunk" ]
    paths-ignore:
      - '.assets'
      - 'README.md'
      - 'CONTRIBUTING.md'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2025, windows-11-arm]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch Latest Paint.NET Release
      id: latest-pdn
      shell: pwsh
      run: |
          $LatestRelease = Invoke-RestMethod -Uri 'https://api.github.com/repos/paintdotnet/release/releases' | Select-Object -First 1
          echo "PDN_VERSION=$($LatestRelease.tag_name)" >> $env:GITHUB_OUTPUT
          $DownloadUrl = $LatestRelease.assets.browser_download_url | Where-Object -FilterScript { $_.EndsWith(".winmsi.$('${{ runner.arch }}'.ToLower()).zip") } | Select-Object -First 1
          echo "PDN_DOWNLOAD=$DownloadUrl" >> $env:GITHUB_OUTPUT

    - name: Cache Dotnet Libraries
      id: cache-dotnet
      uses: actions/cache@v4
      with:
        path: shared/libs
        key: ${{ hashFiles('shared/bridge', 'shared/openraster') }}-${{ steps.latest-pdn.outputs.PDN_VERSION }}-${{ matrix.os }}

    - name: Set dotnet skip
      run: echo "SKIP_DOTNET_BUILDING=${{ steps.cache-dotnet.outputs.cache-hit }}" >> $env:GITHUB_ENV

    - name: Install .NET Core
      if: steps.cache-dotnet.outputs.cache-hit != 'true'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Copy over libnethost to be cached
      if: steps.cache-dotnet.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        $NetHost = Get-ChildItem -Path "C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-$('${{ runner.arch }}'.ToLower())"-Recurse -Include libnethost.lib | Select FullName | Select-Object -Last 1;
        echo $NetHost
        New-Item -Type dir -Force shared\libs
        Copy-Item $NetHost.FullName -Destination "shared\libs\libnethost.lib"

    - name: Install Paint.NET
      if: steps.cache-dotnet.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
          Invoke-RestMethod -Uri '${{ steps.latest-pdn.outputs.PDN_DOWNLOAD }}' -OutFile "paintdotnet.zip"
          Expand-Archive -Path paintdotnet.zip -DestinationPath .\
          $InstallerName = (('${{ steps.latest-pdn.outputs.PDN_DOWNLOAD }}' -split '/' | Select-Object -Last 1) -replace ".zip",".msi")
          Start-Process msiexec -ArgumentList "/i `"$InstallerName`"","/norestart" -Wait;

    - name: Copy over libnethost to netcorehost
      run: cp "shared/libs/libnethost.lib" "libnethost.lib"

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Rust caching
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "v1-rust"

    - name: Build
      run: cargo build --release -F pdn-sys
      env:
        VERSION_NAME: ${{ inputs.version }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PdnBatchConverter-${{ runner.arch }}-${{ github.sha }}
        path: target\release\*.exe
