name: Build Release

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:
    runs-on: windows-2025
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Cache Dotnet Libraries
      id: cache-dotnet
      uses: actions/cache@v4
      with:
        path: shared/libs
        key: ${{ hashFiles('shared/bridge', 'shared/openraster') }}-dotnet

    - name: Set dotnet skip
      run: echo "SKIP_DOTNET_BUILDING=${{ steps.cache-dotnet.outputs.cache-hit }}" >> $GITHUB_ENV

    - name: Install .NET Core
      if: steps.cache-dotnet.outputs.cache-hit != 'true'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install Paint.NET
      if: steps.cache-dotnet.outputs.cache-hit != 'true'
      run: winget install -h -s "winget" -e --id=dotPDN.PaintDotNet

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: cargo build --release -F pdn-sys
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PdnBatchConverter-${{ github.sha }}
        path: target\release\*.exe