<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <RootNamespace>OpenRasterFileType</RootNamespace>
    <AssemblyName>OpenRasterFileType</AssemblyName>
    <Authors>Jarno Ruokamo</Authors>
    <Version>2025.6.17</Version>
    <AssemblyVersion>2025.6.17</AssemblyVersion>
    <FileVersion>2025.6.17</FileVersion>
    <Description>OpenRaster plugin for paint.net</Description>
  </PropertyGroup>
  <ItemGroup>
    <SupportedPlatform Include="windows" />
    <Reference Include="PaintDotNet.Base">
      <Private>false</Private>
      <HintPath>C:\Program Files\Paint.NET\PaintDotNet.Base.dll</HintPath>
    </Reference>
    <Reference Include="PaintDotNet.Core">
      <Private>false</Private>
      <HintPath>C:\Program Files\Paint.NET\PaintDotNet.Core.dll</HintPath>
    </Reference>
    <Reference Include="PaintDotNet.Data">
      <Private>false</Private>
      <HintPath>C:\Program Files\Paint.NET\PaintDotNet.Data.dll</HintPath>
    </Reference>
    <Reference Include="PaintDotNet.Effects">
      <Private>false</Private>
      <HintPath>C:\Program Files\Paint.NET\PaintDotNet.Effects.dll</HintPath>
    </Reference>
    <Reference Include="PaintDotNet.Primitives">
      <Private>false</Private>
      <HintPath>C:\Program Files\Paint.NET\PaintDotNet.Primitives.dll</HintPath>
    </Reference>
    <Reference Include="PaintDotNet.ComponentModel">
      <Private>false</Private>
      <HintPath>C:\Program Files\Paint.NET\PaintDotNet.ComponentModel.dll</HintPath>
    </Reference>
    <Content Include="OraFileType.cs" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.6">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="System.IO.Compression" Version="4.3.0">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>